Use utf-8 instead of utf-8-sig
GwentAPI/arachas pull request #4
Opened 2017-02-01 23:34 UTC by jamieadkins95

Signed-off-by: Jamie Adkins <jamieadkins95@gmail.com>

2017-02-01 23:56 UTC, Tri125 requested changes
Could you perform the same change in indexer.py too?

2017-02-02 00:12 UTC, jamieadkins95 commented
Changed 2 instances in indexer.py 👍

2017-02-02 00:18 UTC, Tri125 commented
In order to document the reason behind the change:
[According to the Unicode standard, the BOM for UTF-8 files is not recommended](https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom).

2017-02-02 00:19 UTC, Tri125 approved these changes

2017-02-02 00:19 UTC, merged